sudu: true

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("pkg")'
script:
  - Rscript -e 'devtools::check("pkg")

after_success:
  - Rscript test/addition_function_test.R